11. The ten emotions of power

"There can be no transforming of darkness into light and of apathy into movement without emotions" -Carl Jung

It's the misconception that we have no control over these mysterious things called emotions.

&nbsp;

Four basic ways in which people deal with emotions

1. Avoidance (you can't avoid feeling)
2. Denial (if the message your emotions are trying to deliver is ignored, the emotions simply increase their amperage; they intensify until you finally pay attention.
3. Competition
4. Learning and using

&nbsp;

The emotions you once thought of as negative are merely a call to action. In fact, instead of calling them negative emotions, from now on  in this chapter, let's call them ACTION SIGNALS.

Once you're familiar with each signal and its message, your emotions become not your enemy but your ally. They become your friend, your mentor, your coach; They guid you through life's most soaring highs and its most demoralising lows.

Realize that the emotions your are feeling at this very moment are a gift, a guideline, a support system, a call to action. If you suppress your emotions and try to drive them out of your life, or if you magnify them and allow them to take over everything, then you're squandering one of life's most precious resources.

You are the source of all emotions; you are the one who creates them.

I'm here to tell you that you can feel any way you choose at any moment in time.

When you do feel good, who's making you feel good? You are!

But you simply have a rule that says you have to wait until A, B, and C occur before you allow yourself to feel good . Why wait?

You d0n't need any special reason to feel good - you can just decide to feel good right now, simply because you're alive, simply because you want to

So if you are the source of all your emotions, why don't you feel good all the time? Again, it's because your so-called negative emotions are giving you a message. What is the message of these Action Signals?

They are telling you that what you're currently doing is not working, that the reason you have pain is either the way you're perceiving things or the procedures you're using: specifically, the way you're communicating your needs and desires to people, or the actions you're taking.

What you're doing is not producing the results you want, and you have to change your approach. Remember that your perceptions are controlled by what you focus on and the meaning you interpret from things

Maybe this ACtion signal of feeling hurt is trying to tell you that you need to change your way of communicating so you don't feel hurt again in the future.

Feeling depressed is another call to action, telling you that you need to change your perception.

Action signals, They are merely trying to support you in talking action to change the way you think, change the way you're perceiving things, or change your procedures for communicating or behaving.

You don't want to be like the fly who keeps banging himself against the window, trying to get through the glass

Your actions signals are whispering to you (perhaps screaming) through the experience of pain, that you need to change what you're doing.

Six steps to emotional mastery

Step 1:  Identify what you're really feeling

Step 2: Acknowledge and appreciate your emotions knowing tehy support you

Step 3: Get curious about the message this emotion is offering you

Step 4: Get confident

Step 5: Get certain you can handle this not only today but in the futre as well

Step: 6: Get Excited, and take action

The Ten Action Signals

1. Discomfort:

The message: boredom, impatience, unease, distress, or mild embarrassment are all sending you a message that somehing is not quite right.

Solution:

a. Use the skills you've already learned in this book to change your state

b. Clarify what you do want; and

c. Refine your action. Try a slightly different approach and see if you can't immediately change the way you're feeling about the situation and/or change the quality of results you're producing

2. Fear

The message: Fear is simply the anticipation that something that's going to happen soon needs to be prepared for. "Be Prepared"

The solution: Review what you were feeling fearfull about and evaluate what you must do to prepare yourself mentally. Figure out what actions you need to take to deal with the situation in the best possible way. Antidote to fear: you must make a decision to have faith.

3. Hurt

The message: Feeling of hurt are usually generated by a sense of loss. The hurt signal gives us is that we have an expectaction that has not been met.

The solution:

a. Realize that in reality you may not have lost anything. Maybe what you need to lose is the false perception.

b. Ask yourself, "is there really loss here? or am I judging this situaiton too soon, or too harshly?"

c. A third solution that can help you get out of a sense of hurt is to elegantly and appropriately communicate your feeling of loss to the person involved.

4. Anger

The message: the message of anger is that an important rule or standard that you hold for your life has been violated by someone else, or maybe even by you.

The solution:

a) Realize that you may have misinterpreted the situation completely, that you anger about this person breaking your rules may be based on the fact that they don't know what's most important to you (even though you believe they should)

b) Realize that even if a person did violate one of your standards, your rules are not necessarily the "right" rules, even though you feel as strongly as you do about them.

c) Ask yourself a more empowering question like "in the logn run, is it true that this person really cares about me?" Interrupt the anger by asking yourself "what can I learn from this?" How can I communicate the importance of these standards I hold for myself to this person in a way that causes them to want to help me, and not violate my standards again in the future?

For exemple if you are angry, change your perception, or change your procedure or change your behaviour.

5. Frustration:

The message: the message of frustration is an exciting signal. It means that your brain believes you could be doing better than you currently are. By contrast, frustration is a very positive sign.

The solutions:

a) Realize that frustration is your friend, and brainstorm new ways to get a result.

b) get some input on how to deal with the situation. Find a role model, someone who has found a way to get what you want.

c) Get fascinated by what you can learn that could help you handle this challenge not only today, but in the future, in a way that consumes very little time or energy and actually creates joy.

6. Disappointment:

The message: disappointment offers you is that an expectation you have had- a goal you were really going for - is probably not going to happen, so it's time to change your expectations to make them more appropriate for this situation and take action to set and achieve a new goal immediately.

The solution:

a) Immediately figure out something you can learn from this situation that could help you in the future to achieve the very thing you were after in the first place.

b) Set a new goal, something that will be even more inspiring and something you can make immediate progress toward.

c) Realize that you may be judging too soon. Often the things you're disappointed about are only temporary challenges, very much like in the story of billy Joel in Chapter 2. As I've said, you and I need to remember that God's delays are not God's denials.

d) Realize that a situation isn't over yet, and develop more patience. Completely reevaluate what you truly want, and begin to develop an even more effective plan for achieving it.

e) Cultivating an attitude of positive expectancy about what will happen in the future, regardless of what has occurred in the past.

7. Guilt

The message: Guilt tells you that you have violated one of your own hightest standards, and that you must do something immediately to ensure that you're not going to violate that standard again in the future.

The solution:

a) Acknowledge that you have, in fact, violated a critical standard you hold for yourself

b) Absolutetly commit yoursefl to making sure this behavior will never happen agaoin in the future. Rehearse in you mind how, if you could live it again, you could deal with the same situation you feel guilty about in a way that is consistent with your own highest personal standards.

8. Inadequacy: Often we have a completely unfaire rule for determining whether we're inadequate or not.

The message: The message is that you don't presently have a level of skill necessary for the task at hand. It's telling you that you need more information, understanding, strategies, tools or confidence.

The solution:

a) Simply ask yourself "Is this really an appropriate emotion for me to feel in this situation?" Am I really inadequate, or do I have to change the way I'm perceiving things?"

If your feelings is justified, the message of inadequacy is that you need to find a way to do something better than you've done it before.

b)Whenever you feel inadequate, appreciate the encouragement to improve. You can begin to feel adequate the moment you decide to commit yourself to CANI- Constant and never-ending improvement in this area.

c) Find a role model - someone who's effective in the area in which you feel inadequate- and get some coaching from them.

9. Overload or overwhelm

The message: The message of being overwhelmed is that you need to reevaluate what's most important to you in this situation.

The solution:

a) Decide, out of all the things you're dealing with in your life, what the absolute, most important things is for you to focus on.

b) Now write down all the things that are most important for you to accomplish and put them in an order of priority. Just putting them down on paper will allow you to begin to feel a sense of control over what's going on.

c) Tackle the first thing on your list, and continue to take action until you've mastered it.

d) When you feel that it's appropriate to start letting go of an overwhelming emotion life grief, start focusing on what you can control and realize that there must be some empowering meaning to it all even though you can't comprehend it yet.

When we create an environment inside our minds that has too many intense and simultaneous demands upon us, of course we'll feel overloaded. But we also have the power to change this by focusing on what we can control and dealing with it a step at a time.

10. Loneliness.

The message: The message for loneliness is that you need a connection with people.

The solution:

a) The solution to loneliness is to realize that you can reach out and make a connection immediately and end the loneliness. There are caring people everywhere

b) Identify what kind of connection you do need.

c) Remind yourself that what's great about being lonely is that it means, "I really care about people, and I love to be with them. I need to find out what kind of connection I need with somebody right now, and then take an action immediately to make that happen".

d) then, take immediate action to reach out and connect with someone.

"We must cultivate our garden"- Voltaire.

The ten emotions of power

1. Love and warmth

"if you could only love enough, you could be the most powerful person in the world" - Emmet fox

2. Appreciation and gratitude

3. Curiosity

if you want to cure boredom , be curious. if you are curious, nothing is a chore.

4. Excitement and passion

Passion is unbridled power to move our lives forward at a faster tempo than ever before.

How do we get passion? The same way we get love, warmth, appreciation, gratefulness and curiosity - we decide to feel it!

Use your physiology: speak more rapidly, visualise images more rapidly, move your body in the direction you want to go. Don't just casually sit and think. You can't be filled with passion if you're slumping over your desk, breathing shallowly, and slurring your speech.

5. Determination:

determination means the difference between being stuck and being struck with the lightning power of commitment.

"Determination is the wake-up call to the human will" - Anthony robbins

Courage is the foundation from which determination is born

6. Flexibility :

Choosing to be flexible is choosing to be happy

7. Confidence

The ability to act on faith is what moves the human race forward

8. Cheerfulness

You've achieved cheerfulness the day you realise that no matter what's happening around you, being anything other than cheerful will not make it better

Being cheerful means you're incredibly intelligent because you know that if you live life in a state of pleasure-one that's so intense that you transmit a sense of joy to those around you- you can have the impact to meet virtually any challenge that comes your way.

9. Vitality

A critical element to physical vitality is ensuring that you have an abundant level of nerve energy

So realize that a sense of vitality is a critical emotion to cultivate in order to handle virtually any emotions than come up in your life.

10. Contribution

What do I need to do to turn my life around?

The secret to living is giving

10 action signals

1. discomfort

2.fear

3. hurt

4. anger

5. frustration

6. disappointement

7. guilt

8. inadequacy

9. overload, overwhelm

10. loneliness

&nbsp;

10 emotions of power

1. love and warmth

2. appreciation and gratitude

3. curiosity

4. excitement and passion

5. determination

6. flexibility

7. confidence

8. cheerfulness

9. vitality

10. contribution

&nbsp;

Plant this emotions daily

TODO

I would now like you to do an assignment that will fully associate you to the simple and powerful tool of emotions

1) Over the next 2 days, any time you feel a disempowering or negative emotion, follow the 6 steps to emotional mastery

2) Aciton signals serve an important function. Cultivate global beliefs that help minimise your experience of the negative emotions. Every feeling that you have - good or bad - is based on your interpretation of what things mean.

Whenever you feel bad, ask yourself this question " What else could this means?"

What we really need is a reason to use the power of our decisions, to change your beliefs, to get leverage on ourselves and interrupt our patterns, to ask better questions and sensitise ourselves to our vocabulary and metaphors.

&nbsp;

&nbsp;

&nbsp;

&nbsp;
